#!/usr/bin/env bash
# deploy_contracts.sh — Build and deploy all LumaBet Soroban contracts
set -euo pipefail

NETWORK="${STELLAR_NETWORK:-testnet}"
RPC_URL="${STELLAR_RPC_URL:-https://soroban-testnet.stellar.org}"
NETWORK_PASSPHRASE="${STELLAR_NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
ADMIN_SECRET="${ADMIN_SECRET_KEY:?ADMIN_SECRET_KEY is required}"

CONTRACTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$(cd "$(dirname "$0")/.." && pwd)/.contract_ids.env"

log() { echo "[deploy] $*"; }
err() { echo "[error]  $*" >&2; exit 1; }

command -v stellar &>/dev/null || err "stellar CLI not found — install from https://stellar.org/cli"
command -v cargo  &>/dev/null || err "cargo not found — install Rust from https://rustup.rs"

log "Network: $NETWORK ($RPC_URL)"
log "Building contracts for wasm32-unknown-unknown..."

build_contract() {
  local name="$1"
  local dir="$CONTRACTS_DIR/$name"
  log "Building $name..."
  (cd "$dir" && cargo build --target wasm32-unknown-unknown --release 2>&1)
  local wasm="$dir/target/wasm32-unknown-unknown/release/$(echo "$name" | tr '-' '_').wasm"
  [[ -f "$wasm" ]] || err "WASM not found at $wasm"
  echo "$wasm"
}

deploy_contract() {
  local name="$1"
  local wasm="$2"
  log "Deploying $name..."
  stellar contract deploy \
    --wasm "$wasm" \
    --source-account "$ADMIN_SECRET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" 2>&1
}

# Build all three contracts
RNG_WASM=$(build_contract "lumabet_rng")
CORE_WASM=$(build_contract "lumabet_core")
DICE_WASM=$(build_contract "lumabet_dice")

# Deploy and capture contract IDs
log "Deploying contracts to $NETWORK..."
RNG_ID=$(deploy_contract "lumabet_rng" "$RNG_WASM")
CORE_ID=$(deploy_contract "lumabet_core" "$CORE_WASM")
DICE_ID=$(deploy_contract "lumabet_dice" "$DICE_WASM")

# Write contract IDs to a .env snippet
cat >"$OUT_FILE" <<EOF
# Auto-generated by deploy_contracts.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
LUMABET_RNG_CONTRACT_ID=$RNG_ID
LUMABET_CORE_CONTRACT_ID=$CORE_ID
LUMABET_DICE_CONTRACT_ID=$DICE_ID
EOF

log "Contract IDs written to $OUT_FILE"
cat "$OUT_FILE"

log "Done! Add these values to your .env files."
